### ISSUE TITLE
plugins para grandnode

### ISSUE THREAD

**Issue by marcelowu** [openponce/vultpay#5]
https://docs.grandnode.com/how-to-create-payment-type-plugin
https://github.com/grandnode/grandnode
ta para fazer amigo

**Comment by diogo-carsys** [comment]
Ola amigo, como vai?
O que vc precisa?

**Comment by marcelowu** [comment]
como integra para ecommerce tipo nopcommerce e grandnode

https://github.com/nopSolutions/nopCommerce
https://github.com/grandnode/grandnode
